### ISSUE TITLE
Decrypting encrypted key creates empty file

### ISSUE THREAD

**Issue by cavejay** [cvidler/rtm_install_key#6]
While attempting to deploy an encrypted key recently I ran into the problem that the key_convert.sh script would not create a usable decrypted key.

I ended up having to decrypt the key using openssl but was momentarily stumped as to why the script fails to do what it says it's doing.

I plan to investigate this on my own but if you (@cvidler) get to it before me feel free.

**Comment by cvidler** [comment]
going to need some diagnostics about the issue to do anything about it.
add -ddd to the command line for extra debug output.
